import { useTranslate } from '@Shared/translate.js';
const { setBulk } = useTranslate();

setBulk({
    en: {
        'tattoo.shop.zone.buy': 'Buy',
        'tattoo.shop.zone.exit': 'Exit',
        'tattoo.shop.zone.torso': 'Torso',
        'tattoo.shop.zone.left.arm': 'Left Arm',
        'tattoo.shop.zone.right.arm': 'Right Arm',
        'tattoo.shop.zone.head': 'Head',
        'tattoo.shop.zone.left.leg': 'Left Leg',
        'tattoo.shop.zone.right.leg': 'Right Leg',
        'tattoo.shop.zone.change': 'Change Zone :',
        'tattoo.shop.collection': 'Collection',
        'tattoo.shop.index': 'Index:',
        'tattoo.shop.price': 'Price:',
        'tattoo.shop.blip.name': 'Tattoo Shop',
        'tattoo.shop.not.enough.money': 'Not enough money',
        'tattoo.shop.notif.title': 'Tattoo Shop',
        'tattoo.shop.notif.subtitle.warning': 'Warning',
        'tattoo.shop.notif.subtitle.succes': 'Succes',
        'tattoo.shop.notif.bought': 'Successful purchase',
        'tattoo.shop.more.options': 'More options',
        'tattoo.shop.delete.all': 'Delete All Tattoos',
        'tattoo.shop.are.you.sure': 'Are you Sure?',
        'tattoo.shop.yes': 'Yes',
        'tattoo.shop.no': 'No',
    },
    hu: {
        'tattoo.shop.zone.buy': 'Vásárlás',
        'tattoo.shop.zone.exit': 'Kilépés',
        'tattoo.shop.zone.torso': 'Felsőtest',
        'tattoo.shop.zone.left.arm': 'Bal kéz',
        'tattoo.shop.zone.right.arm': 'Jobb kéz',
        'tattoo.shop.zone.head': 'Fej/nyak',
        'tattoo.shop.zone.left.leg': 'Bal láb',
        'tattoo.shop.zone.right.leg': 'Jobb láb',
        'tattoo.shop.zone.change': 'Testrész kiválasztása :',
        'tattoo.shop.collection': 'Kollekció',
        'tattoo.shop.index': 'Index:',
        'tattoo.shop.price': 'Ára:',
        'tattoo.shop.blip.name': 'Tetoválószalon',
        'tattoo.shop.not.enough.money': 'Nincs nálad elég pénz',
        'tattoo.shop.notif.title': 'Tetoválószalon',
        'tattoo.shop.notif.subtitle.warning': 'Figyelmeztetés',
        'tattoo.shop.notif.subtitle.succes': 'Siker',
        'tattoo.shop.notif.bought': 'Sikeresen megvetted.',
        'tattoo.shop.more.options': 'További lehetőségek',
        'tattoo.shop.delete.all': 'Összes tetoválás törlése',
        'tattoo.shop.are.you.sure': 'Biztos vagy benne?',
        'tattoo.shop.yes': 'Igen',
        'tattoo.shop.no': 'Nem',

    }
});
